// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: CloudeinAPI.proto
// Original file comments:
// ******************************************************************************
// Created  				Jun 23, 2021
// Modified				Jun 23, 2021
// Version				1.0.0.0
//
// FILE:					CloudeinAPI.proto
// Author:				dhimm@mslm.kr
// DESCRIPTION:			Cloudein TX-SM API grpc proto
// 
// *****************************************************************************
//
#ifndef GRPC_CloudeinAPI_2eproto__INCLUDED
#define GRPC_CloudeinAPI_2eproto__INCLUDED

#include "CloudeinAPI.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace cloudeinapi {

class CloudeinSession final {
 public:
  static constexpr char const* service_full_name() {
    return "cloudeinapi.CloudeinSession";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status DoAllocateAPI(::grpc::ClientContext* context, const ::cloudeinapi::AllocateRequest& request, ::cloudeinapi::AllocateResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cloudeinapi::AllocateResponse>> AsyncDoAllocateAPI(::grpc::ClientContext* context, const ::cloudeinapi::AllocateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cloudeinapi::AllocateResponse>>(AsyncDoAllocateAPIRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cloudeinapi::AllocateResponse>> PrepareAsyncDoAllocateAPI(::grpc::ClientContext* context, const ::cloudeinapi::AllocateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cloudeinapi::AllocateResponse>>(PrepareAsyncDoAllocateAPIRaw(context, request, cq));
    }
    virtual ::grpc::Status DoPrepareAPI(::grpc::ClientContext* context, const ::cloudeinapi::PrepareRequest& request, ::cloudeinapi::PrepareResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cloudeinapi::PrepareResponse>> AsyncDoPrepareAPI(::grpc::ClientContext* context, const ::cloudeinapi::PrepareRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cloudeinapi::PrepareResponse>>(AsyncDoPrepareAPIRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cloudeinapi::PrepareResponse>> PrepareAsyncDoPrepareAPI(::grpc::ClientContext* context, const ::cloudeinapi::PrepareRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cloudeinapi::PrepareResponse>>(PrepareAsyncDoPrepareAPIRaw(context, request, cq));
    }
    virtual ::grpc::Status DoConnectAPI(::grpc::ClientContext* context, const ::cloudeinapi::ConnectRequest& request, ::cloudeinapi::ConnectResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cloudeinapi::ConnectResponse>> AsyncDoConnectAPI(::grpc::ClientContext* context, const ::cloudeinapi::ConnectRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cloudeinapi::ConnectResponse>>(AsyncDoConnectAPIRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cloudeinapi::ConnectResponse>> PrepareAsyncDoConnectAPI(::grpc::ClientContext* context, const ::cloudeinapi::ConnectRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cloudeinapi::ConnectResponse>>(PrepareAsyncDoConnectAPIRaw(context, request, cq));
    }
    virtual ::grpc::Status DoReleaseAPI(::grpc::ClientContext* context, const ::cloudeinapi::ReleaseRequest& request, ::cloudeinapi::ReleaseResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cloudeinapi::ReleaseResponse>> AsyncDoReleaseAPI(::grpc::ClientContext* context, const ::cloudeinapi::ReleaseRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cloudeinapi::ReleaseResponse>>(AsyncDoReleaseAPIRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cloudeinapi::ReleaseResponse>> PrepareAsyncDoReleaseAPI(::grpc::ClientContext* context, const ::cloudeinapi::ReleaseRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::cloudeinapi::ReleaseResponse>>(PrepareAsyncDoReleaseAPIRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void DoAllocateAPI(::grpc::ClientContext* context, const ::cloudeinapi::AllocateRequest* request, ::cloudeinapi::AllocateResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void DoAllocateAPI(::grpc::ClientContext* context, const ::cloudeinapi::AllocateRequest* request, ::cloudeinapi::AllocateResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void DoAllocateAPI(::grpc::ClientContext* context, const ::cloudeinapi::AllocateRequest* request, ::cloudeinapi::AllocateResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void DoPrepareAPI(::grpc::ClientContext* context, const ::cloudeinapi::PrepareRequest* request, ::cloudeinapi::PrepareResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void DoPrepareAPI(::grpc::ClientContext* context, const ::cloudeinapi::PrepareRequest* request, ::cloudeinapi::PrepareResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void DoPrepareAPI(::grpc::ClientContext* context, const ::cloudeinapi::PrepareRequest* request, ::cloudeinapi::PrepareResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void DoConnectAPI(::grpc::ClientContext* context, const ::cloudeinapi::ConnectRequest* request, ::cloudeinapi::ConnectResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void DoConnectAPI(::grpc::ClientContext* context, const ::cloudeinapi::ConnectRequest* request, ::cloudeinapi::ConnectResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void DoConnectAPI(::grpc::ClientContext* context, const ::cloudeinapi::ConnectRequest* request, ::cloudeinapi::ConnectResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void DoReleaseAPI(::grpc::ClientContext* context, const ::cloudeinapi::ReleaseRequest* request, ::cloudeinapi::ReleaseResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void DoReleaseAPI(::grpc::ClientContext* context, const ::cloudeinapi::ReleaseRequest* request, ::cloudeinapi::ReleaseResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void DoReleaseAPI(::grpc::ClientContext* context, const ::cloudeinapi::ReleaseRequest* request, ::cloudeinapi::ReleaseResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::cloudeinapi::AllocateResponse>* AsyncDoAllocateAPIRaw(::grpc::ClientContext* context, const ::cloudeinapi::AllocateRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::cloudeinapi::AllocateResponse>* PrepareAsyncDoAllocateAPIRaw(::grpc::ClientContext* context, const ::cloudeinapi::AllocateRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::cloudeinapi::PrepareResponse>* AsyncDoPrepareAPIRaw(::grpc::ClientContext* context, const ::cloudeinapi::PrepareRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::cloudeinapi::PrepareResponse>* PrepareAsyncDoPrepareAPIRaw(::grpc::ClientContext* context, const ::cloudeinapi::PrepareRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::cloudeinapi::ConnectResponse>* AsyncDoConnectAPIRaw(::grpc::ClientContext* context, const ::cloudeinapi::ConnectRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::cloudeinapi::ConnectResponse>* PrepareAsyncDoConnectAPIRaw(::grpc::ClientContext* context, const ::cloudeinapi::ConnectRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::cloudeinapi::ReleaseResponse>* AsyncDoReleaseAPIRaw(::grpc::ClientContext* context, const ::cloudeinapi::ReleaseRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::cloudeinapi::ReleaseResponse>* PrepareAsyncDoReleaseAPIRaw(::grpc::ClientContext* context, const ::cloudeinapi::ReleaseRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status DoAllocateAPI(::grpc::ClientContext* context, const ::cloudeinapi::AllocateRequest& request, ::cloudeinapi::AllocateResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cloudeinapi::AllocateResponse>> AsyncDoAllocateAPI(::grpc::ClientContext* context, const ::cloudeinapi::AllocateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cloudeinapi::AllocateResponse>>(AsyncDoAllocateAPIRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cloudeinapi::AllocateResponse>> PrepareAsyncDoAllocateAPI(::grpc::ClientContext* context, const ::cloudeinapi::AllocateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cloudeinapi::AllocateResponse>>(PrepareAsyncDoAllocateAPIRaw(context, request, cq));
    }
    ::grpc::Status DoPrepareAPI(::grpc::ClientContext* context, const ::cloudeinapi::PrepareRequest& request, ::cloudeinapi::PrepareResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cloudeinapi::PrepareResponse>> AsyncDoPrepareAPI(::grpc::ClientContext* context, const ::cloudeinapi::PrepareRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cloudeinapi::PrepareResponse>>(AsyncDoPrepareAPIRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cloudeinapi::PrepareResponse>> PrepareAsyncDoPrepareAPI(::grpc::ClientContext* context, const ::cloudeinapi::PrepareRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cloudeinapi::PrepareResponse>>(PrepareAsyncDoPrepareAPIRaw(context, request, cq));
    }
    ::grpc::Status DoConnectAPI(::grpc::ClientContext* context, const ::cloudeinapi::ConnectRequest& request, ::cloudeinapi::ConnectResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cloudeinapi::ConnectResponse>> AsyncDoConnectAPI(::grpc::ClientContext* context, const ::cloudeinapi::ConnectRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cloudeinapi::ConnectResponse>>(AsyncDoConnectAPIRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cloudeinapi::ConnectResponse>> PrepareAsyncDoConnectAPI(::grpc::ClientContext* context, const ::cloudeinapi::ConnectRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cloudeinapi::ConnectResponse>>(PrepareAsyncDoConnectAPIRaw(context, request, cq));
    }
    ::grpc::Status DoReleaseAPI(::grpc::ClientContext* context, const ::cloudeinapi::ReleaseRequest& request, ::cloudeinapi::ReleaseResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cloudeinapi::ReleaseResponse>> AsyncDoReleaseAPI(::grpc::ClientContext* context, const ::cloudeinapi::ReleaseRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cloudeinapi::ReleaseResponse>>(AsyncDoReleaseAPIRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cloudeinapi::ReleaseResponse>> PrepareAsyncDoReleaseAPI(::grpc::ClientContext* context, const ::cloudeinapi::ReleaseRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::cloudeinapi::ReleaseResponse>>(PrepareAsyncDoReleaseAPIRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void DoAllocateAPI(::grpc::ClientContext* context, const ::cloudeinapi::AllocateRequest* request, ::cloudeinapi::AllocateResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void DoAllocateAPI(::grpc::ClientContext* context, const ::cloudeinapi::AllocateRequest* request, ::cloudeinapi::AllocateResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void DoAllocateAPI(::grpc::ClientContext* context, const ::cloudeinapi::AllocateRequest* request, ::cloudeinapi::AllocateResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void DoPrepareAPI(::grpc::ClientContext* context, const ::cloudeinapi::PrepareRequest* request, ::cloudeinapi::PrepareResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void DoPrepareAPI(::grpc::ClientContext* context, const ::cloudeinapi::PrepareRequest* request, ::cloudeinapi::PrepareResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void DoPrepareAPI(::grpc::ClientContext* context, const ::cloudeinapi::PrepareRequest* request, ::cloudeinapi::PrepareResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void DoConnectAPI(::grpc::ClientContext* context, const ::cloudeinapi::ConnectRequest* request, ::cloudeinapi::ConnectResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void DoConnectAPI(::grpc::ClientContext* context, const ::cloudeinapi::ConnectRequest* request, ::cloudeinapi::ConnectResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void DoConnectAPI(::grpc::ClientContext* context, const ::cloudeinapi::ConnectRequest* request, ::cloudeinapi::ConnectResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void DoReleaseAPI(::grpc::ClientContext* context, const ::cloudeinapi::ReleaseRequest* request, ::cloudeinapi::ReleaseResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void DoReleaseAPI(::grpc::ClientContext* context, const ::cloudeinapi::ReleaseRequest* request, ::cloudeinapi::ReleaseResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void DoReleaseAPI(::grpc::ClientContext* context, const ::cloudeinapi::ReleaseRequest* request, ::cloudeinapi::ReleaseResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::cloudeinapi::AllocateResponse>* AsyncDoAllocateAPIRaw(::grpc::ClientContext* context, const ::cloudeinapi::AllocateRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::cloudeinapi::AllocateResponse>* PrepareAsyncDoAllocateAPIRaw(::grpc::ClientContext* context, const ::cloudeinapi::AllocateRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::cloudeinapi::PrepareResponse>* AsyncDoPrepareAPIRaw(::grpc::ClientContext* context, const ::cloudeinapi::PrepareRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::cloudeinapi::PrepareResponse>* PrepareAsyncDoPrepareAPIRaw(::grpc::ClientContext* context, const ::cloudeinapi::PrepareRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::cloudeinapi::ConnectResponse>* AsyncDoConnectAPIRaw(::grpc::ClientContext* context, const ::cloudeinapi::ConnectRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::cloudeinapi::ConnectResponse>* PrepareAsyncDoConnectAPIRaw(::grpc::ClientContext* context, const ::cloudeinapi::ConnectRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::cloudeinapi::ReleaseResponse>* AsyncDoReleaseAPIRaw(::grpc::ClientContext* context, const ::cloudeinapi::ReleaseRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::cloudeinapi::ReleaseResponse>* PrepareAsyncDoReleaseAPIRaw(::grpc::ClientContext* context, const ::cloudeinapi::ReleaseRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_DoAllocateAPI_;
    const ::grpc::internal::RpcMethod rpcmethod_DoPrepareAPI_;
    const ::grpc::internal::RpcMethod rpcmethod_DoConnectAPI_;
    const ::grpc::internal::RpcMethod rpcmethod_DoReleaseAPI_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status DoAllocateAPI(::grpc::ServerContext* context, const ::cloudeinapi::AllocateRequest* request, ::cloudeinapi::AllocateResponse* response);
    virtual ::grpc::Status DoPrepareAPI(::grpc::ServerContext* context, const ::cloudeinapi::PrepareRequest* request, ::cloudeinapi::PrepareResponse* response);
    virtual ::grpc::Status DoConnectAPI(::grpc::ServerContext* context, const ::cloudeinapi::ConnectRequest* request, ::cloudeinapi::ConnectResponse* response);
    virtual ::grpc::Status DoReleaseAPI(::grpc::ServerContext* context, const ::cloudeinapi::ReleaseRequest* request, ::cloudeinapi::ReleaseResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_DoAllocateAPI : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DoAllocateAPI() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_DoAllocateAPI() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DoAllocateAPI(::grpc::ServerContext* /*context*/, const ::cloudeinapi::AllocateRequest* /*request*/, ::cloudeinapi::AllocateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDoAllocateAPI(::grpc::ServerContext* context, ::cloudeinapi::AllocateRequest* request, ::grpc::ServerAsyncResponseWriter< ::cloudeinapi::AllocateResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DoPrepareAPI : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DoPrepareAPI() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_DoPrepareAPI() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DoPrepareAPI(::grpc::ServerContext* /*context*/, const ::cloudeinapi::PrepareRequest* /*request*/, ::cloudeinapi::PrepareResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDoPrepareAPI(::grpc::ServerContext* context, ::cloudeinapi::PrepareRequest* request, ::grpc::ServerAsyncResponseWriter< ::cloudeinapi::PrepareResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DoConnectAPI : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DoConnectAPI() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_DoConnectAPI() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DoConnectAPI(::grpc::ServerContext* /*context*/, const ::cloudeinapi::ConnectRequest* /*request*/, ::cloudeinapi::ConnectResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDoConnectAPI(::grpc::ServerContext* context, ::cloudeinapi::ConnectRequest* request, ::grpc::ServerAsyncResponseWriter< ::cloudeinapi::ConnectResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DoReleaseAPI : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DoReleaseAPI() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_DoReleaseAPI() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DoReleaseAPI(::grpc::ServerContext* /*context*/, const ::cloudeinapi::ReleaseRequest* /*request*/, ::cloudeinapi::ReleaseResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDoReleaseAPI(::grpc::ServerContext* context, ::cloudeinapi::ReleaseRequest* request, ::grpc::ServerAsyncResponseWriter< ::cloudeinapi::ReleaseResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_DoAllocateAPI<WithAsyncMethod_DoPrepareAPI<WithAsyncMethod_DoConnectAPI<WithAsyncMethod_DoReleaseAPI<Service > > > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_DoAllocateAPI : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_DoAllocateAPI() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::cloudeinapi::AllocateRequest, ::cloudeinapi::AllocateResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::cloudeinapi::AllocateRequest* request, ::cloudeinapi::AllocateResponse* response) { return this->DoAllocateAPI(context, request, response); }));}
    void SetMessageAllocatorFor_DoAllocateAPI(
        ::grpc::experimental::MessageAllocator< ::cloudeinapi::AllocateRequest, ::cloudeinapi::AllocateResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::cloudeinapi::AllocateRequest, ::cloudeinapi::AllocateResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_DoAllocateAPI() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DoAllocateAPI(::grpc::ServerContext* /*context*/, const ::cloudeinapi::AllocateRequest* /*request*/, ::cloudeinapi::AllocateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* DoAllocateAPI(
      ::grpc::CallbackServerContext* /*context*/, const ::cloudeinapi::AllocateRequest* /*request*/, ::cloudeinapi::AllocateResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* DoAllocateAPI(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::cloudeinapi::AllocateRequest* /*request*/, ::cloudeinapi::AllocateResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_DoPrepareAPI : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_DoPrepareAPI() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::cloudeinapi::PrepareRequest, ::cloudeinapi::PrepareResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::cloudeinapi::PrepareRequest* request, ::cloudeinapi::PrepareResponse* response) { return this->DoPrepareAPI(context, request, response); }));}
    void SetMessageAllocatorFor_DoPrepareAPI(
        ::grpc::experimental::MessageAllocator< ::cloudeinapi::PrepareRequest, ::cloudeinapi::PrepareResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::cloudeinapi::PrepareRequest, ::cloudeinapi::PrepareResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_DoPrepareAPI() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DoPrepareAPI(::grpc::ServerContext* /*context*/, const ::cloudeinapi::PrepareRequest* /*request*/, ::cloudeinapi::PrepareResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* DoPrepareAPI(
      ::grpc::CallbackServerContext* /*context*/, const ::cloudeinapi::PrepareRequest* /*request*/, ::cloudeinapi::PrepareResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* DoPrepareAPI(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::cloudeinapi::PrepareRequest* /*request*/, ::cloudeinapi::PrepareResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_DoConnectAPI : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_DoConnectAPI() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::cloudeinapi::ConnectRequest, ::cloudeinapi::ConnectResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::cloudeinapi::ConnectRequest* request, ::cloudeinapi::ConnectResponse* response) { return this->DoConnectAPI(context, request, response); }));}
    void SetMessageAllocatorFor_DoConnectAPI(
        ::grpc::experimental::MessageAllocator< ::cloudeinapi::ConnectRequest, ::cloudeinapi::ConnectResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(2);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::cloudeinapi::ConnectRequest, ::cloudeinapi::ConnectResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_DoConnectAPI() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DoConnectAPI(::grpc::ServerContext* /*context*/, const ::cloudeinapi::ConnectRequest* /*request*/, ::cloudeinapi::ConnectResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* DoConnectAPI(
      ::grpc::CallbackServerContext* /*context*/, const ::cloudeinapi::ConnectRequest* /*request*/, ::cloudeinapi::ConnectResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* DoConnectAPI(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::cloudeinapi::ConnectRequest* /*request*/, ::cloudeinapi::ConnectResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_DoReleaseAPI : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_DoReleaseAPI() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::cloudeinapi::ReleaseRequest, ::cloudeinapi::ReleaseResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::cloudeinapi::ReleaseRequest* request, ::cloudeinapi::ReleaseResponse* response) { return this->DoReleaseAPI(context, request, response); }));}
    void SetMessageAllocatorFor_DoReleaseAPI(
        ::grpc::experimental::MessageAllocator< ::cloudeinapi::ReleaseRequest, ::cloudeinapi::ReleaseResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(3);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::cloudeinapi::ReleaseRequest, ::cloudeinapi::ReleaseResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_DoReleaseAPI() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DoReleaseAPI(::grpc::ServerContext* /*context*/, const ::cloudeinapi::ReleaseRequest* /*request*/, ::cloudeinapi::ReleaseResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* DoReleaseAPI(
      ::grpc::CallbackServerContext* /*context*/, const ::cloudeinapi::ReleaseRequest* /*request*/, ::cloudeinapi::ReleaseResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* DoReleaseAPI(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::cloudeinapi::ReleaseRequest* /*request*/, ::cloudeinapi::ReleaseResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_DoAllocateAPI<ExperimentalWithCallbackMethod_DoPrepareAPI<ExperimentalWithCallbackMethod_DoConnectAPI<ExperimentalWithCallbackMethod_DoReleaseAPI<Service > > > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_DoAllocateAPI<ExperimentalWithCallbackMethod_DoPrepareAPI<ExperimentalWithCallbackMethod_DoConnectAPI<ExperimentalWithCallbackMethod_DoReleaseAPI<Service > > > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_DoAllocateAPI : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DoAllocateAPI() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_DoAllocateAPI() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DoAllocateAPI(::grpc::ServerContext* /*context*/, const ::cloudeinapi::AllocateRequest* /*request*/, ::cloudeinapi::AllocateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DoPrepareAPI : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DoPrepareAPI() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_DoPrepareAPI() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DoPrepareAPI(::grpc::ServerContext* /*context*/, const ::cloudeinapi::PrepareRequest* /*request*/, ::cloudeinapi::PrepareResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DoConnectAPI : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DoConnectAPI() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_DoConnectAPI() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DoConnectAPI(::grpc::ServerContext* /*context*/, const ::cloudeinapi::ConnectRequest* /*request*/, ::cloudeinapi::ConnectResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DoReleaseAPI : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DoReleaseAPI() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_DoReleaseAPI() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DoReleaseAPI(::grpc::ServerContext* /*context*/, const ::cloudeinapi::ReleaseRequest* /*request*/, ::cloudeinapi::ReleaseResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_DoAllocateAPI : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DoAllocateAPI() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_DoAllocateAPI() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DoAllocateAPI(::grpc::ServerContext* /*context*/, const ::cloudeinapi::AllocateRequest* /*request*/, ::cloudeinapi::AllocateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDoAllocateAPI(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_DoPrepareAPI : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DoPrepareAPI() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_DoPrepareAPI() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DoPrepareAPI(::grpc::ServerContext* /*context*/, const ::cloudeinapi::PrepareRequest* /*request*/, ::cloudeinapi::PrepareResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDoPrepareAPI(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_DoConnectAPI : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DoConnectAPI() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_DoConnectAPI() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DoConnectAPI(::grpc::ServerContext* /*context*/, const ::cloudeinapi::ConnectRequest* /*request*/, ::cloudeinapi::ConnectResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDoConnectAPI(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_DoReleaseAPI : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DoReleaseAPI() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_DoReleaseAPI() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DoReleaseAPI(::grpc::ServerContext* /*context*/, const ::cloudeinapi::ReleaseRequest* /*request*/, ::cloudeinapi::ReleaseResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDoReleaseAPI(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_DoAllocateAPI : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_DoAllocateAPI() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DoAllocateAPI(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_DoAllocateAPI() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DoAllocateAPI(::grpc::ServerContext* /*context*/, const ::cloudeinapi::AllocateRequest* /*request*/, ::cloudeinapi::AllocateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* DoAllocateAPI(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* DoAllocateAPI(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_DoPrepareAPI : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_DoPrepareAPI() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DoPrepareAPI(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_DoPrepareAPI() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DoPrepareAPI(::grpc::ServerContext* /*context*/, const ::cloudeinapi::PrepareRequest* /*request*/, ::cloudeinapi::PrepareResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* DoPrepareAPI(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* DoPrepareAPI(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_DoConnectAPI : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_DoConnectAPI() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DoConnectAPI(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_DoConnectAPI() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DoConnectAPI(::grpc::ServerContext* /*context*/, const ::cloudeinapi::ConnectRequest* /*request*/, ::cloudeinapi::ConnectResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* DoConnectAPI(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* DoConnectAPI(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_DoReleaseAPI : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_DoReleaseAPI() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DoReleaseAPI(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_DoReleaseAPI() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DoReleaseAPI(::grpc::ServerContext* /*context*/, const ::cloudeinapi::ReleaseRequest* /*request*/, ::cloudeinapi::ReleaseResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* DoReleaseAPI(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* DoReleaseAPI(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DoAllocateAPI : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DoAllocateAPI() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::cloudeinapi::AllocateRequest, ::cloudeinapi::AllocateResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::cloudeinapi::AllocateRequest, ::cloudeinapi::AllocateResponse>* streamer) {
                       return this->StreamedDoAllocateAPI(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DoAllocateAPI() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DoAllocateAPI(::grpc::ServerContext* /*context*/, const ::cloudeinapi::AllocateRequest* /*request*/, ::cloudeinapi::AllocateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDoAllocateAPI(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::cloudeinapi::AllocateRequest,::cloudeinapi::AllocateResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DoPrepareAPI : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DoPrepareAPI() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::cloudeinapi::PrepareRequest, ::cloudeinapi::PrepareResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::cloudeinapi::PrepareRequest, ::cloudeinapi::PrepareResponse>* streamer) {
                       return this->StreamedDoPrepareAPI(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DoPrepareAPI() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DoPrepareAPI(::grpc::ServerContext* /*context*/, const ::cloudeinapi::PrepareRequest* /*request*/, ::cloudeinapi::PrepareResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDoPrepareAPI(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::cloudeinapi::PrepareRequest,::cloudeinapi::PrepareResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DoConnectAPI : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DoConnectAPI() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::cloudeinapi::ConnectRequest, ::cloudeinapi::ConnectResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::cloudeinapi::ConnectRequest, ::cloudeinapi::ConnectResponse>* streamer) {
                       return this->StreamedDoConnectAPI(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DoConnectAPI() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DoConnectAPI(::grpc::ServerContext* /*context*/, const ::cloudeinapi::ConnectRequest* /*request*/, ::cloudeinapi::ConnectResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDoConnectAPI(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::cloudeinapi::ConnectRequest,::cloudeinapi::ConnectResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DoReleaseAPI : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DoReleaseAPI() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::cloudeinapi::ReleaseRequest, ::cloudeinapi::ReleaseResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::cloudeinapi::ReleaseRequest, ::cloudeinapi::ReleaseResponse>* streamer) {
                       return this->StreamedDoReleaseAPI(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DoReleaseAPI() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DoReleaseAPI(::grpc::ServerContext* /*context*/, const ::cloudeinapi::ReleaseRequest* /*request*/, ::cloudeinapi::ReleaseResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDoReleaseAPI(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::cloudeinapi::ReleaseRequest,::cloudeinapi::ReleaseResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_DoAllocateAPI<WithStreamedUnaryMethod_DoPrepareAPI<WithStreamedUnaryMethod_DoConnectAPI<WithStreamedUnaryMethod_DoReleaseAPI<Service > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_DoAllocateAPI<WithStreamedUnaryMethod_DoPrepareAPI<WithStreamedUnaryMethod_DoConnectAPI<WithStreamedUnaryMethod_DoReleaseAPI<Service > > > > StreamedService;
};

}  // namespace cloudeinapi


#endif  // GRPC_CloudeinAPI_2eproto__INCLUDED
