// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CloudeinAPI.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_CloudeinAPI_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_CloudeinAPI_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3015000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3015008 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_CloudeinAPI_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_CloudeinAPI_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[8]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_CloudeinAPI_2eproto;
::PROTOBUF_NAMESPACE_ID::Metadata descriptor_table_CloudeinAPI_2eproto_metadata_getter(int index);
namespace cloudeinapi {
class AllocateRequest;
struct AllocateRequestDefaultTypeInternal;
extern AllocateRequestDefaultTypeInternal _AllocateRequest_default_instance_;
class AllocateResponse;
struct AllocateResponseDefaultTypeInternal;
extern AllocateResponseDefaultTypeInternal _AllocateResponse_default_instance_;
class ConnectRequest;
struct ConnectRequestDefaultTypeInternal;
extern ConnectRequestDefaultTypeInternal _ConnectRequest_default_instance_;
class ConnectResponse;
struct ConnectResponseDefaultTypeInternal;
extern ConnectResponseDefaultTypeInternal _ConnectResponse_default_instance_;
class PrepareRequest;
struct PrepareRequestDefaultTypeInternal;
extern PrepareRequestDefaultTypeInternal _PrepareRequest_default_instance_;
class PrepareResponse;
struct PrepareResponseDefaultTypeInternal;
extern PrepareResponseDefaultTypeInternal _PrepareResponse_default_instance_;
class ReleaseRequest;
struct ReleaseRequestDefaultTypeInternal;
extern ReleaseRequestDefaultTypeInternal _ReleaseRequest_default_instance_;
class ReleaseResponse;
struct ReleaseResponseDefaultTypeInternal;
extern ReleaseResponseDefaultTypeInternal _ReleaseResponse_default_instance_;
}  // namespace cloudeinapi
PROTOBUF_NAMESPACE_OPEN
template<> ::cloudeinapi::AllocateRequest* Arena::CreateMaybeMessage<::cloudeinapi::AllocateRequest>(Arena*);
template<> ::cloudeinapi::AllocateResponse* Arena::CreateMaybeMessage<::cloudeinapi::AllocateResponse>(Arena*);
template<> ::cloudeinapi::ConnectRequest* Arena::CreateMaybeMessage<::cloudeinapi::ConnectRequest>(Arena*);
template<> ::cloudeinapi::ConnectResponse* Arena::CreateMaybeMessage<::cloudeinapi::ConnectResponse>(Arena*);
template<> ::cloudeinapi::PrepareRequest* Arena::CreateMaybeMessage<::cloudeinapi::PrepareRequest>(Arena*);
template<> ::cloudeinapi::PrepareResponse* Arena::CreateMaybeMessage<::cloudeinapi::PrepareResponse>(Arena*);
template<> ::cloudeinapi::ReleaseRequest* Arena::CreateMaybeMessage<::cloudeinapi::ReleaseRequest>(Arena*);
template<> ::cloudeinapi::ReleaseResponse* Arena::CreateMaybeMessage<::cloudeinapi::ReleaseResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace cloudeinapi {

// ===================================================================

class AllocateRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cloudeinapi.AllocateRequest) */ {
 public:
  inline AllocateRequest() : AllocateRequest(nullptr) {}
  virtual ~AllocateRequest();
  explicit constexpr AllocateRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AllocateRequest(const AllocateRequest& from);
  AllocateRequest(AllocateRequest&& from) noexcept
    : AllocateRequest() {
    *this = ::std::move(from);
  }

  inline AllocateRequest& operator=(const AllocateRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline AllocateRequest& operator=(AllocateRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const AllocateRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const AllocateRequest* internal_default_instance() {
    return reinterpret_cast<const AllocateRequest*>(
               &_AllocateRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(AllocateRequest& a, AllocateRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(AllocateRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AllocateRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline AllocateRequest* New() const final {
    return CreateMaybeMessage<AllocateRequest>(nullptr);
  }

  AllocateRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<AllocateRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const AllocateRequest& from);
  void MergeFrom(const AllocateRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AllocateRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cloudeinapi.AllocateRequest";
  }
  protected:
  explicit AllocateRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_CloudeinAPI_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRegionFieldNumber = 1,
    kTxNameFieldNumber = 2,
  };
  // string region = 1;
  void clear_region();
  const std::string& region() const;
  void set_region(const std::string& value);
  void set_region(std::string&& value);
  void set_region(const char* value);
  void set_region(const char* value, size_t size);
  std::string* mutable_region();
  std::string* release_region();
  void set_allocated_region(std::string* region);
  private:
  const std::string& _internal_region() const;
  void _internal_set_region(const std::string& value);
  std::string* _internal_mutable_region();
  public:

  // string tx_name = 2;
  void clear_tx_name();
  const std::string& tx_name() const;
  void set_tx_name(const std::string& value);
  void set_tx_name(std::string&& value);
  void set_tx_name(const char* value);
  void set_tx_name(const char* value, size_t size);
  std::string* mutable_tx_name();
  std::string* release_tx_name();
  void set_allocated_tx_name(std::string* tx_name);
  private:
  const std::string& _internal_tx_name() const;
  void _internal_set_tx_name(const std::string& value);
  std::string* _internal_mutable_tx_name();
  public:

  // @@protoc_insertion_point(class_scope:cloudeinapi.AllocateRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr region_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr tx_name_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_CloudeinAPI_2eproto;
};
// -------------------------------------------------------------------

class AllocateResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cloudeinapi.AllocateResponse) */ {
 public:
  inline AllocateResponse() : AllocateResponse(nullptr) {}
  virtual ~AllocateResponse();
  explicit constexpr AllocateResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AllocateResponse(const AllocateResponse& from);
  AllocateResponse(AllocateResponse&& from) noexcept
    : AllocateResponse() {
    *this = ::std::move(from);
  }

  inline AllocateResponse& operator=(const AllocateResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline AllocateResponse& operator=(AllocateResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const AllocateResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const AllocateResponse* internal_default_instance() {
    return reinterpret_cast<const AllocateResponse*>(
               &_AllocateResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(AllocateResponse& a, AllocateResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(AllocateResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AllocateResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline AllocateResponse* New() const final {
    return CreateMaybeMessage<AllocateResponse>(nullptr);
  }

  AllocateResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<AllocateResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const AllocateResponse& from);
  void MergeFrom(const AllocateResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AllocateResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cloudeinapi.AllocateResponse";
  }
  protected:
  explicit AllocateResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_CloudeinAPI_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRegionFieldNumber = 1,
    kAllocatePort1FieldNumber = 11,
    kAllocatePort2FieldNumber = 12,
    kAllocatePort3FieldNumber = 13,
    kAllocatePort4FieldNumber = 14,
    kAllocatePort5FieldNumber = 15,
  };
  // string region = 1;
  void clear_region();
  const std::string& region() const;
  void set_region(const std::string& value);
  void set_region(std::string&& value);
  void set_region(const char* value);
  void set_region(const char* value, size_t size);
  std::string* mutable_region();
  std::string* release_region();
  void set_allocated_region(std::string* region);
  private:
  const std::string& _internal_region() const;
  void _internal_set_region(const std::string& value);
  std::string* _internal_mutable_region();
  public:

  // uint64 allocate_port1 = 11;
  void clear_allocate_port1();
  ::PROTOBUF_NAMESPACE_ID::uint64 allocate_port1() const;
  void set_allocate_port1(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_allocate_port1() const;
  void _internal_set_allocate_port1(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 allocate_port2 = 12;
  void clear_allocate_port2();
  ::PROTOBUF_NAMESPACE_ID::uint64 allocate_port2() const;
  void set_allocate_port2(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_allocate_port2() const;
  void _internal_set_allocate_port2(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 allocate_port3 = 13;
  void clear_allocate_port3();
  ::PROTOBUF_NAMESPACE_ID::uint64 allocate_port3() const;
  void set_allocate_port3(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_allocate_port3() const;
  void _internal_set_allocate_port3(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 allocate_port4 = 14;
  void clear_allocate_port4();
  ::PROTOBUF_NAMESPACE_ID::uint64 allocate_port4() const;
  void set_allocate_port4(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_allocate_port4() const;
  void _internal_set_allocate_port4(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 allocate_port5 = 15;
  void clear_allocate_port5();
  ::PROTOBUF_NAMESPACE_ID::uint64 allocate_port5() const;
  void set_allocate_port5(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_allocate_port5() const;
  void _internal_set_allocate_port5(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:cloudeinapi.AllocateResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr region_;
  ::PROTOBUF_NAMESPACE_ID::uint64 allocate_port1_;
  ::PROTOBUF_NAMESPACE_ID::uint64 allocate_port2_;
  ::PROTOBUF_NAMESPACE_ID::uint64 allocate_port3_;
  ::PROTOBUF_NAMESPACE_ID::uint64 allocate_port4_;
  ::PROTOBUF_NAMESPACE_ID::uint64 allocate_port5_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_CloudeinAPI_2eproto;
};
// -------------------------------------------------------------------

class PrepareRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cloudeinapi.PrepareRequest) */ {
 public:
  inline PrepareRequest() : PrepareRequest(nullptr) {}
  virtual ~PrepareRequest();
  explicit constexpr PrepareRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PrepareRequest(const PrepareRequest& from);
  PrepareRequest(PrepareRequest&& from) noexcept
    : PrepareRequest() {
    *this = ::std::move(from);
  }

  inline PrepareRequest& operator=(const PrepareRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline PrepareRequest& operator=(PrepareRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PrepareRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const PrepareRequest* internal_default_instance() {
    return reinterpret_cast<const PrepareRequest*>(
               &_PrepareRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(PrepareRequest& a, PrepareRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(PrepareRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PrepareRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PrepareRequest* New() const final {
    return CreateMaybeMessage<PrepareRequest>(nullptr);
  }

  PrepareRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PrepareRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PrepareRequest& from);
  void MergeFrom(const PrepareRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PrepareRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cloudeinapi.PrepareRequest";
  }
  protected:
  explicit PrepareRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_CloudeinAPI_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRegionFieldNumber = 1,
    kTxNameFieldNumber = 2,
  };
  // string region = 1;
  void clear_region();
  const std::string& region() const;
  void set_region(const std::string& value);
  void set_region(std::string&& value);
  void set_region(const char* value);
  void set_region(const char* value, size_t size);
  std::string* mutable_region();
  std::string* release_region();
  void set_allocated_region(std::string* region);
  private:
  const std::string& _internal_region() const;
  void _internal_set_region(const std::string& value);
  std::string* _internal_mutable_region();
  public:

  // string tx_name = 2;
  void clear_tx_name();
  const std::string& tx_name() const;
  void set_tx_name(const std::string& value);
  void set_tx_name(std::string&& value);
  void set_tx_name(const char* value);
  void set_tx_name(const char* value, size_t size);
  std::string* mutable_tx_name();
  std::string* release_tx_name();
  void set_allocated_tx_name(std::string* tx_name);
  private:
  const std::string& _internal_tx_name() const;
  void _internal_set_tx_name(const std::string& value);
  std::string* _internal_mutable_tx_name();
  public:

  // @@protoc_insertion_point(class_scope:cloudeinapi.PrepareRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr region_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr tx_name_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_CloudeinAPI_2eproto;
};
// -------------------------------------------------------------------

class PrepareResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cloudeinapi.PrepareResponse) */ {
 public:
  inline PrepareResponse() : PrepareResponse(nullptr) {}
  virtual ~PrepareResponse();
  explicit constexpr PrepareResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PrepareResponse(const PrepareResponse& from);
  PrepareResponse(PrepareResponse&& from) noexcept
    : PrepareResponse() {
    *this = ::std::move(from);
  }

  inline PrepareResponse& operator=(const PrepareResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline PrepareResponse& operator=(PrepareResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PrepareResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const PrepareResponse* internal_default_instance() {
    return reinterpret_cast<const PrepareResponse*>(
               &_PrepareResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(PrepareResponse& a, PrepareResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(PrepareResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PrepareResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PrepareResponse* New() const final {
    return CreateMaybeMessage<PrepareResponse>(nullptr);
  }

  PrepareResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PrepareResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PrepareResponse& from);
  void MergeFrom(const PrepareResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PrepareResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cloudeinapi.PrepareResponse";
  }
  protected:
  explicit PrepareResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_CloudeinAPI_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRegionFieldNumber = 1,
  };
  // string region = 1;
  void clear_region();
  const std::string& region() const;
  void set_region(const std::string& value);
  void set_region(std::string&& value);
  void set_region(const char* value);
  void set_region(const char* value, size_t size);
  std::string* mutable_region();
  std::string* release_region();
  void set_allocated_region(std::string* region);
  private:
  const std::string& _internal_region() const;
  void _internal_set_region(const std::string& value);
  std::string* _internal_mutable_region();
  public:

  // @@protoc_insertion_point(class_scope:cloudeinapi.PrepareResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr region_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_CloudeinAPI_2eproto;
};
// -------------------------------------------------------------------

class ConnectRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cloudeinapi.ConnectRequest) */ {
 public:
  inline ConnectRequest() : ConnectRequest(nullptr) {}
  virtual ~ConnectRequest();
  explicit constexpr ConnectRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ConnectRequest(const ConnectRequest& from);
  ConnectRequest(ConnectRequest&& from) noexcept
    : ConnectRequest() {
    *this = ::std::move(from);
  }

  inline ConnectRequest& operator=(const ConnectRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ConnectRequest& operator=(ConnectRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ConnectRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ConnectRequest* internal_default_instance() {
    return reinterpret_cast<const ConnectRequest*>(
               &_ConnectRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(ConnectRequest& a, ConnectRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ConnectRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ConnectRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ConnectRequest* New() const final {
    return CreateMaybeMessage<ConnectRequest>(nullptr);
  }

  ConnectRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ConnectRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ConnectRequest& from);
  void MergeFrom(const ConnectRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ConnectRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cloudeinapi.ConnectRequest";
  }
  protected:
  explicit ConnectRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_CloudeinAPI_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRegionFieldNumber = 1,
    kTxNameFieldNumber = 2,
  };
  // string region = 1;
  void clear_region();
  const std::string& region() const;
  void set_region(const std::string& value);
  void set_region(std::string&& value);
  void set_region(const char* value);
  void set_region(const char* value, size_t size);
  std::string* mutable_region();
  std::string* release_region();
  void set_allocated_region(std::string* region);
  private:
  const std::string& _internal_region() const;
  void _internal_set_region(const std::string& value);
  std::string* _internal_mutable_region();
  public:

  // string tx_name = 2;
  void clear_tx_name();
  const std::string& tx_name() const;
  void set_tx_name(const std::string& value);
  void set_tx_name(std::string&& value);
  void set_tx_name(const char* value);
  void set_tx_name(const char* value, size_t size);
  std::string* mutable_tx_name();
  std::string* release_tx_name();
  void set_allocated_tx_name(std::string* tx_name);
  private:
  const std::string& _internal_tx_name() const;
  void _internal_set_tx_name(const std::string& value);
  std::string* _internal_mutable_tx_name();
  public:

  // @@protoc_insertion_point(class_scope:cloudeinapi.ConnectRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr region_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr tx_name_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_CloudeinAPI_2eproto;
};
// -------------------------------------------------------------------

class ConnectResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cloudeinapi.ConnectResponse) */ {
 public:
  inline ConnectResponse() : ConnectResponse(nullptr) {}
  virtual ~ConnectResponse();
  explicit constexpr ConnectResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ConnectResponse(const ConnectResponse& from);
  ConnectResponse(ConnectResponse&& from) noexcept
    : ConnectResponse() {
    *this = ::std::move(from);
  }

  inline ConnectResponse& operator=(const ConnectResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ConnectResponse& operator=(ConnectResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ConnectResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ConnectResponse* internal_default_instance() {
    return reinterpret_cast<const ConnectResponse*>(
               &_ConnectResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(ConnectResponse& a, ConnectResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ConnectResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ConnectResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ConnectResponse* New() const final {
    return CreateMaybeMessage<ConnectResponse>(nullptr);
  }

  ConnectResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ConnectResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ConnectResponse& from);
  void MergeFrom(const ConnectResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ConnectResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cloudeinapi.ConnectResponse";
  }
  protected:
  explicit ConnectResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_CloudeinAPI_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRegionFieldNumber = 1,
  };
  // string region = 1;
  void clear_region();
  const std::string& region() const;
  void set_region(const std::string& value);
  void set_region(std::string&& value);
  void set_region(const char* value);
  void set_region(const char* value, size_t size);
  std::string* mutable_region();
  std::string* release_region();
  void set_allocated_region(std::string* region);
  private:
  const std::string& _internal_region() const;
  void _internal_set_region(const std::string& value);
  std::string* _internal_mutable_region();
  public:

  // @@protoc_insertion_point(class_scope:cloudeinapi.ConnectResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr region_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_CloudeinAPI_2eproto;
};
// -------------------------------------------------------------------

class ReleaseRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cloudeinapi.ReleaseRequest) */ {
 public:
  inline ReleaseRequest() : ReleaseRequest(nullptr) {}
  virtual ~ReleaseRequest();
  explicit constexpr ReleaseRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ReleaseRequest(const ReleaseRequest& from);
  ReleaseRequest(ReleaseRequest&& from) noexcept
    : ReleaseRequest() {
    *this = ::std::move(from);
  }

  inline ReleaseRequest& operator=(const ReleaseRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReleaseRequest& operator=(ReleaseRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ReleaseRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ReleaseRequest* internal_default_instance() {
    return reinterpret_cast<const ReleaseRequest*>(
               &_ReleaseRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(ReleaseRequest& a, ReleaseRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ReleaseRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReleaseRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ReleaseRequest* New() const final {
    return CreateMaybeMessage<ReleaseRequest>(nullptr);
  }

  ReleaseRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ReleaseRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ReleaseRequest& from);
  void MergeFrom(const ReleaseRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReleaseRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cloudeinapi.ReleaseRequest";
  }
  protected:
  explicit ReleaseRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_CloudeinAPI_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRegionFieldNumber = 1,
    kTxNameFieldNumber = 2,
  };
  // string region = 1;
  void clear_region();
  const std::string& region() const;
  void set_region(const std::string& value);
  void set_region(std::string&& value);
  void set_region(const char* value);
  void set_region(const char* value, size_t size);
  std::string* mutable_region();
  std::string* release_region();
  void set_allocated_region(std::string* region);
  private:
  const std::string& _internal_region() const;
  void _internal_set_region(const std::string& value);
  std::string* _internal_mutable_region();
  public:

  // string tx_name = 2;
  void clear_tx_name();
  const std::string& tx_name() const;
  void set_tx_name(const std::string& value);
  void set_tx_name(std::string&& value);
  void set_tx_name(const char* value);
  void set_tx_name(const char* value, size_t size);
  std::string* mutable_tx_name();
  std::string* release_tx_name();
  void set_allocated_tx_name(std::string* tx_name);
  private:
  const std::string& _internal_tx_name() const;
  void _internal_set_tx_name(const std::string& value);
  std::string* _internal_mutable_tx_name();
  public:

  // @@protoc_insertion_point(class_scope:cloudeinapi.ReleaseRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr region_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr tx_name_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_CloudeinAPI_2eproto;
};
// -------------------------------------------------------------------

class ReleaseResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:cloudeinapi.ReleaseResponse) */ {
 public:
  inline ReleaseResponse() : ReleaseResponse(nullptr) {}
  virtual ~ReleaseResponse();
  explicit constexpr ReleaseResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ReleaseResponse(const ReleaseResponse& from);
  ReleaseResponse(ReleaseResponse&& from) noexcept
    : ReleaseResponse() {
    *this = ::std::move(from);
  }

  inline ReleaseResponse& operator=(const ReleaseResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReleaseResponse& operator=(ReleaseResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ReleaseResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ReleaseResponse* internal_default_instance() {
    return reinterpret_cast<const ReleaseResponse*>(
               &_ReleaseResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(ReleaseResponse& a, ReleaseResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ReleaseResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReleaseResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ReleaseResponse* New() const final {
    return CreateMaybeMessage<ReleaseResponse>(nullptr);
  }

  ReleaseResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ReleaseResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ReleaseResponse& from);
  void MergeFrom(const ReleaseResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReleaseResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "cloudeinapi.ReleaseResponse";
  }
  protected:
  explicit ReleaseResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_CloudeinAPI_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRegionFieldNumber = 1,
  };
  // string region = 1;
  void clear_region();
  const std::string& region() const;
  void set_region(const std::string& value);
  void set_region(std::string&& value);
  void set_region(const char* value);
  void set_region(const char* value, size_t size);
  std::string* mutable_region();
  std::string* release_region();
  void set_allocated_region(std::string* region);
  private:
  const std::string& _internal_region() const;
  void _internal_set_region(const std::string& value);
  std::string* _internal_mutable_region();
  public:

  // @@protoc_insertion_point(class_scope:cloudeinapi.ReleaseResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr region_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_CloudeinAPI_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AllocateRequest

// string region = 1;
inline void AllocateRequest::clear_region() {
  region_.ClearToEmpty();
}
inline const std::string& AllocateRequest::region() const {
  // @@protoc_insertion_point(field_get:cloudeinapi.AllocateRequest.region)
  return _internal_region();
}
inline void AllocateRequest::set_region(const std::string& value) {
  _internal_set_region(value);
  // @@protoc_insertion_point(field_set:cloudeinapi.AllocateRequest.region)
}
inline std::string* AllocateRequest::mutable_region() {
  // @@protoc_insertion_point(field_mutable:cloudeinapi.AllocateRequest.region)
  return _internal_mutable_region();
}
inline const std::string& AllocateRequest::_internal_region() const {
  return region_.Get();
}
inline void AllocateRequest::_internal_set_region(const std::string& value) {
  
  region_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void AllocateRequest::set_region(std::string&& value) {
  
  region_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:cloudeinapi.AllocateRequest.region)
}
inline void AllocateRequest::set_region(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  region_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:cloudeinapi.AllocateRequest.region)
}
inline void AllocateRequest::set_region(const char* value,
    size_t size) {
  
  region_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:cloudeinapi.AllocateRequest.region)
}
inline std::string* AllocateRequest::_internal_mutable_region() {
  
  return region_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* AllocateRequest::release_region() {
  // @@protoc_insertion_point(field_release:cloudeinapi.AllocateRequest.region)
  return region_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void AllocateRequest::set_allocated_region(std::string* region) {
  if (region != nullptr) {
    
  } else {
    
  }
  region_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), region,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:cloudeinapi.AllocateRequest.region)
}

// string tx_name = 2;
inline void AllocateRequest::clear_tx_name() {
  tx_name_.ClearToEmpty();
}
inline const std::string& AllocateRequest::tx_name() const {
  // @@protoc_insertion_point(field_get:cloudeinapi.AllocateRequest.tx_name)
  return _internal_tx_name();
}
inline void AllocateRequest::set_tx_name(const std::string& value) {
  _internal_set_tx_name(value);
  // @@protoc_insertion_point(field_set:cloudeinapi.AllocateRequest.tx_name)
}
inline std::string* AllocateRequest::mutable_tx_name() {
  // @@protoc_insertion_point(field_mutable:cloudeinapi.AllocateRequest.tx_name)
  return _internal_mutable_tx_name();
}
inline const std::string& AllocateRequest::_internal_tx_name() const {
  return tx_name_.Get();
}
inline void AllocateRequest::_internal_set_tx_name(const std::string& value) {
  
  tx_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void AllocateRequest::set_tx_name(std::string&& value) {
  
  tx_name_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:cloudeinapi.AllocateRequest.tx_name)
}
inline void AllocateRequest::set_tx_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  tx_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:cloudeinapi.AllocateRequest.tx_name)
}
inline void AllocateRequest::set_tx_name(const char* value,
    size_t size) {
  
  tx_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:cloudeinapi.AllocateRequest.tx_name)
}
inline std::string* AllocateRequest::_internal_mutable_tx_name() {
  
  return tx_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* AllocateRequest::release_tx_name() {
  // @@protoc_insertion_point(field_release:cloudeinapi.AllocateRequest.tx_name)
  return tx_name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void AllocateRequest::set_allocated_tx_name(std::string* tx_name) {
  if (tx_name != nullptr) {
    
  } else {
    
  }
  tx_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), tx_name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:cloudeinapi.AllocateRequest.tx_name)
}

// -------------------------------------------------------------------

// AllocateResponse

// string region = 1;
inline void AllocateResponse::clear_region() {
  region_.ClearToEmpty();
}
inline const std::string& AllocateResponse::region() const {
  // @@protoc_insertion_point(field_get:cloudeinapi.AllocateResponse.region)
  return _internal_region();
}
inline void AllocateResponse::set_region(const std::string& value) {
  _internal_set_region(value);
  // @@protoc_insertion_point(field_set:cloudeinapi.AllocateResponse.region)
}
inline std::string* AllocateResponse::mutable_region() {
  // @@protoc_insertion_point(field_mutable:cloudeinapi.AllocateResponse.region)
  return _internal_mutable_region();
}
inline const std::string& AllocateResponse::_internal_region() const {
  return region_.Get();
}
inline void AllocateResponse::_internal_set_region(const std::string& value) {
  
  region_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void AllocateResponse::set_region(std::string&& value) {
  
  region_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:cloudeinapi.AllocateResponse.region)
}
inline void AllocateResponse::set_region(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  region_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:cloudeinapi.AllocateResponse.region)
}
inline void AllocateResponse::set_region(const char* value,
    size_t size) {
  
  region_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:cloudeinapi.AllocateResponse.region)
}
inline std::string* AllocateResponse::_internal_mutable_region() {
  
  return region_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* AllocateResponse::release_region() {
  // @@protoc_insertion_point(field_release:cloudeinapi.AllocateResponse.region)
  return region_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void AllocateResponse::set_allocated_region(std::string* region) {
  if (region != nullptr) {
    
  } else {
    
  }
  region_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), region,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:cloudeinapi.AllocateResponse.region)
}

// uint64 allocate_port1 = 11;
inline void AllocateResponse::clear_allocate_port1() {
  allocate_port1_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 AllocateResponse::_internal_allocate_port1() const {
  return allocate_port1_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 AllocateResponse::allocate_port1() const {
  // @@protoc_insertion_point(field_get:cloudeinapi.AllocateResponse.allocate_port1)
  return _internal_allocate_port1();
}
inline void AllocateResponse::_internal_set_allocate_port1(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  allocate_port1_ = value;
}
inline void AllocateResponse::set_allocate_port1(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_allocate_port1(value);
  // @@protoc_insertion_point(field_set:cloudeinapi.AllocateResponse.allocate_port1)
}

// uint64 allocate_port2 = 12;
inline void AllocateResponse::clear_allocate_port2() {
  allocate_port2_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 AllocateResponse::_internal_allocate_port2() const {
  return allocate_port2_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 AllocateResponse::allocate_port2() const {
  // @@protoc_insertion_point(field_get:cloudeinapi.AllocateResponse.allocate_port2)
  return _internal_allocate_port2();
}
inline void AllocateResponse::_internal_set_allocate_port2(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  allocate_port2_ = value;
}
inline void AllocateResponse::set_allocate_port2(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_allocate_port2(value);
  // @@protoc_insertion_point(field_set:cloudeinapi.AllocateResponse.allocate_port2)
}

// uint64 allocate_port3 = 13;
inline void AllocateResponse::clear_allocate_port3() {
  allocate_port3_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 AllocateResponse::_internal_allocate_port3() const {
  return allocate_port3_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 AllocateResponse::allocate_port3() const {
  // @@protoc_insertion_point(field_get:cloudeinapi.AllocateResponse.allocate_port3)
  return _internal_allocate_port3();
}
inline void AllocateResponse::_internal_set_allocate_port3(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  allocate_port3_ = value;
}
inline void AllocateResponse::set_allocate_port3(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_allocate_port3(value);
  // @@protoc_insertion_point(field_set:cloudeinapi.AllocateResponse.allocate_port3)
}

// uint64 allocate_port4 = 14;
inline void AllocateResponse::clear_allocate_port4() {
  allocate_port4_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 AllocateResponse::_internal_allocate_port4() const {
  return allocate_port4_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 AllocateResponse::allocate_port4() const {
  // @@protoc_insertion_point(field_get:cloudeinapi.AllocateResponse.allocate_port4)
  return _internal_allocate_port4();
}
inline void AllocateResponse::_internal_set_allocate_port4(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  allocate_port4_ = value;
}
inline void AllocateResponse::set_allocate_port4(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_allocate_port4(value);
  // @@protoc_insertion_point(field_set:cloudeinapi.AllocateResponse.allocate_port4)
}

// uint64 allocate_port5 = 15;
inline void AllocateResponse::clear_allocate_port5() {
  allocate_port5_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 AllocateResponse::_internal_allocate_port5() const {
  return allocate_port5_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 AllocateResponse::allocate_port5() const {
  // @@protoc_insertion_point(field_get:cloudeinapi.AllocateResponse.allocate_port5)
  return _internal_allocate_port5();
}
inline void AllocateResponse::_internal_set_allocate_port5(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  allocate_port5_ = value;
}
inline void AllocateResponse::set_allocate_port5(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_allocate_port5(value);
  // @@protoc_insertion_point(field_set:cloudeinapi.AllocateResponse.allocate_port5)
}

// -------------------------------------------------------------------

// PrepareRequest

// string region = 1;
inline void PrepareRequest::clear_region() {
  region_.ClearToEmpty();
}
inline const std::string& PrepareRequest::region() const {
  // @@protoc_insertion_point(field_get:cloudeinapi.PrepareRequest.region)
  return _internal_region();
}
inline void PrepareRequest::set_region(const std::string& value) {
  _internal_set_region(value);
  // @@protoc_insertion_point(field_set:cloudeinapi.PrepareRequest.region)
}
inline std::string* PrepareRequest::mutable_region() {
  // @@protoc_insertion_point(field_mutable:cloudeinapi.PrepareRequest.region)
  return _internal_mutable_region();
}
inline const std::string& PrepareRequest::_internal_region() const {
  return region_.Get();
}
inline void PrepareRequest::_internal_set_region(const std::string& value) {
  
  region_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void PrepareRequest::set_region(std::string&& value) {
  
  region_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:cloudeinapi.PrepareRequest.region)
}
inline void PrepareRequest::set_region(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  region_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:cloudeinapi.PrepareRequest.region)
}
inline void PrepareRequest::set_region(const char* value,
    size_t size) {
  
  region_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:cloudeinapi.PrepareRequest.region)
}
inline std::string* PrepareRequest::_internal_mutable_region() {
  
  return region_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* PrepareRequest::release_region() {
  // @@protoc_insertion_point(field_release:cloudeinapi.PrepareRequest.region)
  return region_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PrepareRequest::set_allocated_region(std::string* region) {
  if (region != nullptr) {
    
  } else {
    
  }
  region_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), region,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:cloudeinapi.PrepareRequest.region)
}

// string tx_name = 2;
inline void PrepareRequest::clear_tx_name() {
  tx_name_.ClearToEmpty();
}
inline const std::string& PrepareRequest::tx_name() const {
  // @@protoc_insertion_point(field_get:cloudeinapi.PrepareRequest.tx_name)
  return _internal_tx_name();
}
inline void PrepareRequest::set_tx_name(const std::string& value) {
  _internal_set_tx_name(value);
  // @@protoc_insertion_point(field_set:cloudeinapi.PrepareRequest.tx_name)
}
inline std::string* PrepareRequest::mutable_tx_name() {
  // @@protoc_insertion_point(field_mutable:cloudeinapi.PrepareRequest.tx_name)
  return _internal_mutable_tx_name();
}
inline const std::string& PrepareRequest::_internal_tx_name() const {
  return tx_name_.Get();
}
inline void PrepareRequest::_internal_set_tx_name(const std::string& value) {
  
  tx_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void PrepareRequest::set_tx_name(std::string&& value) {
  
  tx_name_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:cloudeinapi.PrepareRequest.tx_name)
}
inline void PrepareRequest::set_tx_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  tx_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:cloudeinapi.PrepareRequest.tx_name)
}
inline void PrepareRequest::set_tx_name(const char* value,
    size_t size) {
  
  tx_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:cloudeinapi.PrepareRequest.tx_name)
}
inline std::string* PrepareRequest::_internal_mutable_tx_name() {
  
  return tx_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* PrepareRequest::release_tx_name() {
  // @@protoc_insertion_point(field_release:cloudeinapi.PrepareRequest.tx_name)
  return tx_name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PrepareRequest::set_allocated_tx_name(std::string* tx_name) {
  if (tx_name != nullptr) {
    
  } else {
    
  }
  tx_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), tx_name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:cloudeinapi.PrepareRequest.tx_name)
}

// -------------------------------------------------------------------

// PrepareResponse

// string region = 1;
inline void PrepareResponse::clear_region() {
  region_.ClearToEmpty();
}
inline const std::string& PrepareResponse::region() const {
  // @@protoc_insertion_point(field_get:cloudeinapi.PrepareResponse.region)
  return _internal_region();
}
inline void PrepareResponse::set_region(const std::string& value) {
  _internal_set_region(value);
  // @@protoc_insertion_point(field_set:cloudeinapi.PrepareResponse.region)
}
inline std::string* PrepareResponse::mutable_region() {
  // @@protoc_insertion_point(field_mutable:cloudeinapi.PrepareResponse.region)
  return _internal_mutable_region();
}
inline const std::string& PrepareResponse::_internal_region() const {
  return region_.Get();
}
inline void PrepareResponse::_internal_set_region(const std::string& value) {
  
  region_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void PrepareResponse::set_region(std::string&& value) {
  
  region_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:cloudeinapi.PrepareResponse.region)
}
inline void PrepareResponse::set_region(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  region_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:cloudeinapi.PrepareResponse.region)
}
inline void PrepareResponse::set_region(const char* value,
    size_t size) {
  
  region_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:cloudeinapi.PrepareResponse.region)
}
inline std::string* PrepareResponse::_internal_mutable_region() {
  
  return region_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* PrepareResponse::release_region() {
  // @@protoc_insertion_point(field_release:cloudeinapi.PrepareResponse.region)
  return region_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PrepareResponse::set_allocated_region(std::string* region) {
  if (region != nullptr) {
    
  } else {
    
  }
  region_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), region,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:cloudeinapi.PrepareResponse.region)
}

// -------------------------------------------------------------------

// ConnectRequest

// string region = 1;
inline void ConnectRequest::clear_region() {
  region_.ClearToEmpty();
}
inline const std::string& ConnectRequest::region() const {
  // @@protoc_insertion_point(field_get:cloudeinapi.ConnectRequest.region)
  return _internal_region();
}
inline void ConnectRequest::set_region(const std::string& value) {
  _internal_set_region(value);
  // @@protoc_insertion_point(field_set:cloudeinapi.ConnectRequest.region)
}
inline std::string* ConnectRequest::mutable_region() {
  // @@protoc_insertion_point(field_mutable:cloudeinapi.ConnectRequest.region)
  return _internal_mutable_region();
}
inline const std::string& ConnectRequest::_internal_region() const {
  return region_.Get();
}
inline void ConnectRequest::_internal_set_region(const std::string& value) {
  
  region_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void ConnectRequest::set_region(std::string&& value) {
  
  region_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:cloudeinapi.ConnectRequest.region)
}
inline void ConnectRequest::set_region(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  region_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:cloudeinapi.ConnectRequest.region)
}
inline void ConnectRequest::set_region(const char* value,
    size_t size) {
  
  region_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:cloudeinapi.ConnectRequest.region)
}
inline std::string* ConnectRequest::_internal_mutable_region() {
  
  return region_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* ConnectRequest::release_region() {
  // @@protoc_insertion_point(field_release:cloudeinapi.ConnectRequest.region)
  return region_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ConnectRequest::set_allocated_region(std::string* region) {
  if (region != nullptr) {
    
  } else {
    
  }
  region_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), region,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:cloudeinapi.ConnectRequest.region)
}

// string tx_name = 2;
inline void ConnectRequest::clear_tx_name() {
  tx_name_.ClearToEmpty();
}
inline const std::string& ConnectRequest::tx_name() const {
  // @@protoc_insertion_point(field_get:cloudeinapi.ConnectRequest.tx_name)
  return _internal_tx_name();
}
inline void ConnectRequest::set_tx_name(const std::string& value) {
  _internal_set_tx_name(value);
  // @@protoc_insertion_point(field_set:cloudeinapi.ConnectRequest.tx_name)
}
inline std::string* ConnectRequest::mutable_tx_name() {
  // @@protoc_insertion_point(field_mutable:cloudeinapi.ConnectRequest.tx_name)
  return _internal_mutable_tx_name();
}
inline const std::string& ConnectRequest::_internal_tx_name() const {
  return tx_name_.Get();
}
inline void ConnectRequest::_internal_set_tx_name(const std::string& value) {
  
  tx_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void ConnectRequest::set_tx_name(std::string&& value) {
  
  tx_name_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:cloudeinapi.ConnectRequest.tx_name)
}
inline void ConnectRequest::set_tx_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  tx_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:cloudeinapi.ConnectRequest.tx_name)
}
inline void ConnectRequest::set_tx_name(const char* value,
    size_t size) {
  
  tx_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:cloudeinapi.ConnectRequest.tx_name)
}
inline std::string* ConnectRequest::_internal_mutable_tx_name() {
  
  return tx_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* ConnectRequest::release_tx_name() {
  // @@protoc_insertion_point(field_release:cloudeinapi.ConnectRequest.tx_name)
  return tx_name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ConnectRequest::set_allocated_tx_name(std::string* tx_name) {
  if (tx_name != nullptr) {
    
  } else {
    
  }
  tx_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), tx_name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:cloudeinapi.ConnectRequest.tx_name)
}

// -------------------------------------------------------------------

// ConnectResponse

// string region = 1;
inline void ConnectResponse::clear_region() {
  region_.ClearToEmpty();
}
inline const std::string& ConnectResponse::region() const {
  // @@protoc_insertion_point(field_get:cloudeinapi.ConnectResponse.region)
  return _internal_region();
}
inline void ConnectResponse::set_region(const std::string& value) {
  _internal_set_region(value);
  // @@protoc_insertion_point(field_set:cloudeinapi.ConnectResponse.region)
}
inline std::string* ConnectResponse::mutable_region() {
  // @@protoc_insertion_point(field_mutable:cloudeinapi.ConnectResponse.region)
  return _internal_mutable_region();
}
inline const std::string& ConnectResponse::_internal_region() const {
  return region_.Get();
}
inline void ConnectResponse::_internal_set_region(const std::string& value) {
  
  region_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void ConnectResponse::set_region(std::string&& value) {
  
  region_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:cloudeinapi.ConnectResponse.region)
}
inline void ConnectResponse::set_region(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  region_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:cloudeinapi.ConnectResponse.region)
}
inline void ConnectResponse::set_region(const char* value,
    size_t size) {
  
  region_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:cloudeinapi.ConnectResponse.region)
}
inline std::string* ConnectResponse::_internal_mutable_region() {
  
  return region_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* ConnectResponse::release_region() {
  // @@protoc_insertion_point(field_release:cloudeinapi.ConnectResponse.region)
  return region_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ConnectResponse::set_allocated_region(std::string* region) {
  if (region != nullptr) {
    
  } else {
    
  }
  region_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), region,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:cloudeinapi.ConnectResponse.region)
}

// -------------------------------------------------------------------

// ReleaseRequest

// string region = 1;
inline void ReleaseRequest::clear_region() {
  region_.ClearToEmpty();
}
inline const std::string& ReleaseRequest::region() const {
  // @@protoc_insertion_point(field_get:cloudeinapi.ReleaseRequest.region)
  return _internal_region();
}
inline void ReleaseRequest::set_region(const std::string& value) {
  _internal_set_region(value);
  // @@protoc_insertion_point(field_set:cloudeinapi.ReleaseRequest.region)
}
inline std::string* ReleaseRequest::mutable_region() {
  // @@protoc_insertion_point(field_mutable:cloudeinapi.ReleaseRequest.region)
  return _internal_mutable_region();
}
inline const std::string& ReleaseRequest::_internal_region() const {
  return region_.Get();
}
inline void ReleaseRequest::_internal_set_region(const std::string& value) {
  
  region_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void ReleaseRequest::set_region(std::string&& value) {
  
  region_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:cloudeinapi.ReleaseRequest.region)
}
inline void ReleaseRequest::set_region(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  region_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:cloudeinapi.ReleaseRequest.region)
}
inline void ReleaseRequest::set_region(const char* value,
    size_t size) {
  
  region_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:cloudeinapi.ReleaseRequest.region)
}
inline std::string* ReleaseRequest::_internal_mutable_region() {
  
  return region_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* ReleaseRequest::release_region() {
  // @@protoc_insertion_point(field_release:cloudeinapi.ReleaseRequest.region)
  return region_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ReleaseRequest::set_allocated_region(std::string* region) {
  if (region != nullptr) {
    
  } else {
    
  }
  region_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), region,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:cloudeinapi.ReleaseRequest.region)
}

// string tx_name = 2;
inline void ReleaseRequest::clear_tx_name() {
  tx_name_.ClearToEmpty();
}
inline const std::string& ReleaseRequest::tx_name() const {
  // @@protoc_insertion_point(field_get:cloudeinapi.ReleaseRequest.tx_name)
  return _internal_tx_name();
}
inline void ReleaseRequest::set_tx_name(const std::string& value) {
  _internal_set_tx_name(value);
  // @@protoc_insertion_point(field_set:cloudeinapi.ReleaseRequest.tx_name)
}
inline std::string* ReleaseRequest::mutable_tx_name() {
  // @@protoc_insertion_point(field_mutable:cloudeinapi.ReleaseRequest.tx_name)
  return _internal_mutable_tx_name();
}
inline const std::string& ReleaseRequest::_internal_tx_name() const {
  return tx_name_.Get();
}
inline void ReleaseRequest::_internal_set_tx_name(const std::string& value) {
  
  tx_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void ReleaseRequest::set_tx_name(std::string&& value) {
  
  tx_name_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:cloudeinapi.ReleaseRequest.tx_name)
}
inline void ReleaseRequest::set_tx_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  tx_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:cloudeinapi.ReleaseRequest.tx_name)
}
inline void ReleaseRequest::set_tx_name(const char* value,
    size_t size) {
  
  tx_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:cloudeinapi.ReleaseRequest.tx_name)
}
inline std::string* ReleaseRequest::_internal_mutable_tx_name() {
  
  return tx_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* ReleaseRequest::release_tx_name() {
  // @@protoc_insertion_point(field_release:cloudeinapi.ReleaseRequest.tx_name)
  return tx_name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ReleaseRequest::set_allocated_tx_name(std::string* tx_name) {
  if (tx_name != nullptr) {
    
  } else {
    
  }
  tx_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), tx_name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:cloudeinapi.ReleaseRequest.tx_name)
}

// -------------------------------------------------------------------

// ReleaseResponse

// string region = 1;
inline void ReleaseResponse::clear_region() {
  region_.ClearToEmpty();
}
inline const std::string& ReleaseResponse::region() const {
  // @@protoc_insertion_point(field_get:cloudeinapi.ReleaseResponse.region)
  return _internal_region();
}
inline void ReleaseResponse::set_region(const std::string& value) {
  _internal_set_region(value);
  // @@protoc_insertion_point(field_set:cloudeinapi.ReleaseResponse.region)
}
inline std::string* ReleaseResponse::mutable_region() {
  // @@protoc_insertion_point(field_mutable:cloudeinapi.ReleaseResponse.region)
  return _internal_mutable_region();
}
inline const std::string& ReleaseResponse::_internal_region() const {
  return region_.Get();
}
inline void ReleaseResponse::_internal_set_region(const std::string& value) {
  
  region_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void ReleaseResponse::set_region(std::string&& value) {
  
  region_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:cloudeinapi.ReleaseResponse.region)
}
inline void ReleaseResponse::set_region(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  region_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:cloudeinapi.ReleaseResponse.region)
}
inline void ReleaseResponse::set_region(const char* value,
    size_t size) {
  
  region_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:cloudeinapi.ReleaseResponse.region)
}
inline std::string* ReleaseResponse::_internal_mutable_region() {
  
  return region_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* ReleaseResponse::release_region() {
  // @@protoc_insertion_point(field_release:cloudeinapi.ReleaseResponse.region)
  return region_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ReleaseResponse::set_allocated_region(std::string* region) {
  if (region != nullptr) {
    
  } else {
    
  }
  region_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), region,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:cloudeinapi.ReleaseResponse.region)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace cloudeinapi

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_CloudeinAPI_2eproto
